section .data
; syscall values
SYS_READ          equ 0
SYS_WRITE         equ 1
SYS_OPEN          equ 2
SYS_CLOSE         equ 3
SYS_FSTAT         equ 5
SYS_LSEEK         equ 8
SYS_SOCKET        equ 41
SYS_CONNECT       equ 42
SYS_ACCEPT        equ 43
SYS_SENDTO        equ 44
SYS_RECVFROM      equ 45
SYS_BIND          equ 49
SYS_LISTEN        equ 50
SYS_GETPEERNAME   equ 52
SYS_SETSOCKOPT    equ 54
SYS_FORK          equ 57
SYS_EXIT          equ 60
SYS_GETDENTS      equ 78
SYS_CLOCK_GETTIME equ 228

